name:                improg
version:             0.1.0.0
github:              alexrichrd/ImProg-F
license:             BSD3
author:              S. Haller, O. Katz, L. Ljubuncic, A. Richard, I. Suslov
maintainer:          alexander.richard@gmx.net
copyright:           2022 S. Haller, O. Katz, L. Ljubuncic, A. Richard, I. Suslov

synopsis:            Implementation of the functional language F


extra-source-files:
- README.md

dependencies:
- base >= 4.13

default-extensions:
- NamedFieldPuns

library:
  source-dirs: src
  exposed-modules:
    - Compiler
    - Declarations
    - MF
    - Parser
    - Store
    - Tokenizer

executables:
  improg:
    main:            Main.hs
    source-dirs:     app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - improg

tests:
  improg-test:
    main:            Spec.hs
    source-dirs:     test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - improg
      - tasty
      - tasty-hunit
